from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_brush = QtWidgets.QAction(MainWindow)
        self.action_brush.setCheckable(False)
        self.action_brush.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/paintbrush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_brush.setIcon(icon)
        self.action_brush.setObjectName("action_brush")
        self.action_line = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/lin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_line.setIcon(icon1)
        self.action_line.setObjectName("action_line")
        self.action_circle = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_circle.setIcon(icon2)
        self.action_circle.setObjectName("action_circle")
        self.action_color = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/colors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_color.setIcon(icon3)
        self.action_color.setObjectName("action_color")
        self.action_rubber = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/rubber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rubber.setIcon(icon4)
        self.action_rubber.setObjectName("action_rubber")
        self.action_saveas = QtWidgets.QAction(MainWindow)
        self.action_saveas.setObjectName("action_saveas")
        self.action_save = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon5)
        self.action_save.setObjectName("action_save")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_thickness = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/thickness.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_thickness.setIcon(icon6)
        self.action_thickness.setObjectName("action_thickness")
        self.action_cancel = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/canceled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cancel.setIcon(icon7)
        self.action_cancel.setObjectName("action_cancel")
        self.action_repeat = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/canceled_reverse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_repeat.setIcon(icon8)
        self.action_repeat.setObjectName("action_repeat")
        self.action_rect = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/rect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rect.setIcon(icon9)
        self.action_rect.setObjectName("action_rect")
        self.action_square = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_square.setIcon(icon10)
        self.action_square.setObjectName("action_square")
        self.action_triangle = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/triangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_triangle.setIcon(icon11)
        self.action_triangle.setObjectName("action_triangle")
        self.action_sq_triangle = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/sq_triangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sq_triangle.setIcon(icon12)
        self.action_sq_triangle.setObjectName("action_sq_triangle")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action_brush)
        self.menu.addAction(self.action_line)
        self.menu.addAction(self.action_circle)
        self.menu.addAction(self.action_square)
        self.menu.addAction(self.action_rect)
        self.menu.addAction(self.action_color)
        self.menu.addAction(self.action_rubber)
        self.menu.addAction(self.action_thickness)
        self.menu.addAction(self.action_cancel)
        self.menu.addAction(self.action_repeat)
        self.menu.addAction(self.action_triangle)
        self.menu.addAction(self.action_sq_triangle)
        self.menu_3.addAction(self.action)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_2.addAction(self.action_new)
        self.menu_2.addAction(self.action_open)
        self.menu_2.addAction(self.action_saveas)
        self.menu_2.addAction(self.action_save)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.action_save)
        self.toolBar.addAction(self.action_cancel)
        self.toolBar.addAction(self.action_repeat)
        self.toolBar.addAction(self.action_brush)
        self.toolBar.addAction(self.action_line)
        self.toolBar.addAction(self.action_circle)
        self.toolBar.addAction(self.action_triangle)
        self.toolBar.addAction(self.action_sq_triangle)
        self.toolBar.addAction(self.action_rect)
        self.toolBar.addAction(self.action_square)
        self.toolBar.addAction(self.action_rubber)
        self.toolBar.addAction(self.action_color)
        self.toolBar.addAction(self.action_thickness)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рисовалка"))
        self.menu.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu_2.setTitle(_translate("MainWindow", "Файл"))
        self.menu_3.setTitle(_translate("MainWindow", "Недавние"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_brush.setText(_translate("MainWindow", "Кисть"))
        self.action_line.setText(_translate("MainWindow", "Линия"))
        self.action_circle.setText(_translate("MainWindow", "Окружность"))
        self.action_color.setText(_translate("MainWindow", "Цвет"))
        self.action_rubber.setText(_translate("MainWindow", "Ластик"))
        self.action_saveas.setText(_translate("MainWindow", "Сохранить как"))
        self.action_save.setText(_translate("MainWindow", "Сохранить"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_open.setText(_translate("MainWindow", "Открыть"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_new.setText(_translate("MainWindow", "Новый"))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_thickness.setText(_translate("MainWindow", "Толщина"))
        self.action_cancel.setText(_translate("MainWindow", "Отменить"))
        self.action_cancel.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_repeat.setText(_translate("MainWindow", "Повторить"))
        self.action_repeat.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_rect.setText(_translate("MainWindow", "Прямоугольник"))
        self.action_square.setText(_translate("MainWindow", "Квадрат"))
        self.action_triangle.setText(_translate("MainWindow", "Треугольник"))
        self.action_sq_triangle.setText(_translate("MainWindow", "Пр. Треугольник"))
        self.action.setText(_translate("MainWindow", "-"))
        self.action_2.setText(_translate("MainWindow", "-"))
        self.action_3.setText(_translate("MainWindow", "-"))
        self.action_4.setText(_translate("MainWindow", "-"))
        self.action_5.setText(_translate("MainWindow", "-"))
